# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: COVID19 Decision Analysis
email: patrick.bryant@scilifelab.se
description: > # this means to ignore newlines until "baseurl:"
  Visualizations for COVID19 data analysis. The analysis focuses on elucidating decision making by authorities and the decisions effects.
baseurl: "/COVID19.github.io" # the subpath of your site, e.g. /blog
url: "https://github.com/patrickbryant1/COVID19.github.io/docs" # the base hostname & protocol for your site
github_username:  patrickbryant1

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
# Build settings
remote_theme: "ecds/digitaledition-jekylltheme "
